apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edusphere-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: edusphere.local # Change this to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edusphere-service
            port:
              number: 80
